---
- hosts: localhost
  vars_prompt:
    - name: git_username
      prompt: 'Enter your Git username'
      private: no

    - name: git_email
      prompt: 'Enter your Git email'
      private: no

  roles:
    - common
    - { role: thinkpad, when: "'ThinkPad' in ansible_product_version" }
    - development-core
    - development-java
    - development-python
    - development-typescript
    - desktop-i3
