---
- name: Configure home workstation
  hosts: localhost
  vars_prompt:
    - name: git_username
      prompt: 'Enter your Git username'
      private: false

    - name: git_email
      prompt: 'Enter your Git email'
      private: false

  roles:
    - common
    - { role: thinkpad, when: "'ThinkPad' in ansible_product_version" }
    - development-core
    - development-java
    - development-python
    - development-typescript
    - development-kubernetes
    - desktop-i3
