- name: Add VS Code repository (RHEL-based systems)
  ansible.builtin.yum_repository:
    name: vs-code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: true
  become: true
  when: ansible_os_family == "RedHat"

- name: Add VS Code Repository (Debian-Systems)
  ansible.builtin.deb822_repository:
    name: vscode
    types: deb
    uris: 'https://packages.microsoft.com/repos/vscode'
    signed_by: 'https://packages.microsoft.com/keys/microsoft.asc'
    suites: stable
    components:
      - main
    architectures: amd64
    state: present
    enabled: true
  become: true
  when: ansible_os_family == "Debian"

- name: Install Development packages
  ansible.builtin.package:
    name:
      - ansible-lint
      - git
      - jq
      - shellcheck
      - shfmt
      - vim
    state: present
  become: true

- name: Install Visual Studio Code (RedHat-Systems)
  ansible.builtin.package:
    name: code
    state: present
  become: true
  when: ansible_os_family == "RedHat"

- name: Install Visual Studio Code (Debian-Systems)
  ansible.builtin.package:
    name: visual-studio-code
    state: present
    update_cache: true
  become: true
  when: ansible_os_family == "Debian"

- name: Install Development packages (Debian-Systems)
  ansible.builtin.package:
    name:
      - build-essential
    state: present
  become: true

- name: Set Git global username
  community.general.git_config:
    name: user.name
    value: "{{ lookup('community.general.onepassword', onepassword_ssh_key_name, field='git_username') }}"
    scope: global

- name: Set Git global email
  community.general.git_config:
    name: user.email
    value: "{{ lookup('community.general.onepassword', onepassword_ssh_key_name, field='email') }}"
    scope: global
