- name: Add VS Code repository (RHEL-based systems)
  ansible.builtin.yum_repository:
    name: vs-code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: true
  become: true
  when: ansible_os_family == "RedHat"

- name: Add VS Code repository (Debian-based systems)
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present
    filename: vscode
  become: true
  when: ansible_os_family == "Debian"

- name: Add VS Code GPG key (Debian-based systems)
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: Install Development packages
  ansible.builtin.package:
    name:
      - ansible
      - ansible-lint
      - code
      - git
      - jq
      - shellcheck
      - vim
    state: present
  become: true

- name: Set Git global username
  ansible.builtin.git_config:
    name: user.name
    value: '{{ git_username }}'
    scope: global
  when: git_username is defined and git_username | length > 0

- name: Set Git global email
  ansible.builtin.git_config:
    name: user.email
    value: '{{ git_email }}'
    scope: global
  when: git_email is defined and git_email | length > 0
