---
- name: Install Java development packages on RHEL-based systems
  ansible.builtin.dnf:
    name:
      - java-{{ openjdk_version }}-openjdk
      - java-{{ openjdk_version }}-openjdk-javadoc
      - java-{{ openjdk_version }}-openjdk-jmods
      - java-{{ openjdk_version }}-openjdk-devel
    state: present
  become: true
  when: ansible_os_family == "RedHat"

- name: Install Java development packages on Debian-based systems
  ansible.builtin.apt:
    name:
      - openjdk-{{ openjdk_version }}-jdk
      - openjdk-{{ openjdk_version }}-jre
      - openjdk-{{ openjdk_version }}-source
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: Set current java version in alternatives on RHEL-based systems
  community.general.alternatives:
    name: java
    path: /usr/lib/jvm/java-{{ openjdk_version }}-openjdk/bin/java
    link: /usr/bin/java
  become: true
  when: ansible_os_family == "RedHat"

- name: Set current java version in alternatives on Debian-based systems
  community.general.alternatives:
    name: java
    path: /usr/lib/jvm/java-{{ openjdk_version }}-openjdk-amd64/bin/java
    link: /usr/bin/java
  become: true
  when: ansible_os_family == "Debian"
