#!/usr/bin/env bash
# .bash_profile

if [ -f /opt/homebrew/bin/brew ]; then
	eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# Function to add a directory to PATH if it's not already included
pathmunge() {
	if ! echo "$PATH" | grep -qE "(^|:)$1($|:)"; then
		if [ "$2" = "after" ]; then
			PATH="$PATH:$1"
		else
			PATH="$1:$PATH"
		fi
	fi
	export PATH
}

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	# shellcheck disable=SC1090
	. ~/.bashrc
fi

# User specific environment and startup programs
if [ -d "/etc/alternatives/java_sdk" ]; then
	export JAVA_HOME="/etc/alternatives/java_sdk"
fi

# Set GTK theme on linux systems
if [ -f /etc/os-release ]; then
	export GTK_THEME=Adwaita-dark
fi

export GPG_TTY=$(tty)
