# K8s repos
- name: Add kubernetes repository (RedHat Systems)
  ansible.builtin.yum_repository:
    name: kubernetes
    description: 'Kubernetes'
    baseurl: https://pkgs.k8s.io/core:/stable:/v1.32/rpm/
    enabled: true
    gpgcheck: true
    gpgkey: https://pkgs.k8s.io/core:/stable:/v1.32/rpm/repodata/repomd.xml.key
    file: kubernetes
  become: true
  when: ansible_distribution in ["RedHat", "CentOS", "Fedora"]

- name: Add kubernetes repository (Debian-Systems)
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /
    state: present
    filename: kubernetes
  become: true
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Add kubernetes GPG key (Debian-Systems)
  ansible.builtin.apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
    state: present
  become: true
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Install packages
  ansible.builtin.package:
    name:
      - kubectl
    state: present
  become: true

- name: Check if Helm is installed
  ansible.builtin.stat:
    path: '{{ ansible_env.HOME }}/.local/bin/helm'
    checksum_algorithm: sha256
  register: helm_stat

- name: Get Helm checksum
  ansible.builtin.set_fact:
    helm_checksum: '{{ helm_stat.stat.checksum }}'
  when: helm_stat.stat.exists

- name: Download Helm
  ansible.builtin.get_url:
    url: 'https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz'
    dest: /tmp/helm.tar.gz
    mode: '0660'
  when: helm_checksum is undefined or helm_checksum != helm_sha256
  register: helm_downloaded

- name: Extract Helm
  ansible.builtin.unarchive:
    src: /tmp/helm.tar.gz
    dest: /tmp/
    remote_src: true
  when: helm_downloaded is defined
  register: helm_extracted

- name: Move Helm binary
  ansible.builtin.copy:
    src: /tmp/linux-amd64/helm
    dest: '{{ ansible_env.HOME }}/.local/bin/helm'
    mode: '0755'
    owner: '{{ ansible_env.USER }}'
    group: '{{ ansible_env.USER }}'
  when: helm_extracted is defined
