- name: Retrieve git credentials
  ansible.builtin.set_fact:
    ssh_key: "{{ lookup('community.general.onepassword_ssh_key', onepassword_ssh_key_name, ssh_format=true) }}"
    ssh_public_key: "{{ lookup('community.general.onepassword', onepassword_ssh_key_name, field='public_key') }}"

- name: Validate ~/.ssh folder exists with proper permisions
  ansible.builtin.file:
    path: ~/.ssh
    mode: '0700'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    state: directory

- name: Ensure ~/.ssh/id_ed25519 key exists and is same as 1password
  ansible.builtin.copy:
    dest: ~/.ssh/id_ed25519
    mode: '0600'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    content: "{{ ssh_key }}"

- name: Ensure ~/.ssh/id_ed25519.pub key exists and is same as 1password
  ansible.builtin.copy:
    dest: ~/.ssh/id_ed25519.pub
    mode: '0644'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    content: "{{ ssh_public_key }}"
